
version: 2

models:

  - name: early_shipments
    description: "early shipment has shipment_date less than 6 days after the order_date and delivery_date is NOT NULL"
    tests:
      - unique
      - not_null

  - name: late_shipments
    description: "late shipment has shipment_date greater than or equal to 6 days after the order_date and delivery_date is NULL"
    tests:
      - unique
      - not_null

  - name: highest_review_product
    description: "product with the highest number of review"
    tests:
      - unique
      - not_null

  - name: undelivered_shipments
    description: "undelivered shipment is one with delivery_date as NULL and shipment_date as NULL and the current_date 15 days after order_date"
    tests:
      - unique
      - not_null

  - name: best_performing_product
    description: "Best performing product by the highest number of reviews percentage distribution of reviews etc"
    tests:
      - unique
      - not_null

  - name: agg_shipments
    description: "Total number of late and undelivered shipments"
    tests:
      - unique
      - not_null

  - name: agg_public_holiday
    description: "Total number of orders during the public holday for the last year"
    tests:
      - unique
      - not_null